name: spindle-simulations
channels:
  - defaults
  - conda-forge
dependencies:
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.4=py311hca03da5_0
  - asttokens=3.0.0=py311hca03da5_0
  - blas=2.138=openblas
  - blas-devel=3.9.0=38_h11c0a38_openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - comm=0.2.1=py311hca03da5_0
  - contourpy=1.3.1=py311h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py311h50f4ffc_1
  - decorator=5.2.1=py311hca03da5_0
  - executing=2.2.1=py311hca03da5_0
  - expat=2.7.3=h982b769_0
  - ffmpeg=6.1.1=h7693a39_3
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=py311h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gdk-pixbuf=2.42.10=h969f7ef_2
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - glib=2.84.4=h863a760_0
  - glib-tools=2.84.4=hff4a405_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - iniconfig=2.1.0=py311hca03da5_0
  - ipydatawidgets=4.3.2=pyhc268e32_0
  - ipykernel=6.30.1=py311hca03da5_0
  - ipympl=0.9.8=pyhcf101f3_0
  - ipython=9.5.0=py311hca03da5_0
  - ipython_pygments_lexers=1.1.1=py311hca03da5_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - jedi=0.19.2=py311hca03da5_0
  - jpeg=9f=h2f69dba_0
  - jupyter_client=8.6.3=py311hca03da5_0
  - jupyter_core=5.8.1=py311hca03da5_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.8=py311h313beb8_0
  - lame=3.100=h1a28f6b_0
  - lcms2=2.16=he26ebf3_1
  - leptonica=1.82.0=hdedf53e_3
  - lerc=4.0.0=h313beb8_0
  - libarchive=3.8.2=ha845c4f_0
  - libavif=1.1.1=h80987f9_0
  - libblas=3.9.0=38_h51639a9_openblas
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblapacke=3.9.0=38_h1b118fd_openblas
  - libogg=1.3.5=h1a28f6b_1
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopenjpeg=2.5.4=haa24f5a_1
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.50=h5c318fc_0
  - librsvg=2.56.3=h38920c8_2
  - libsodium=1.0.20=h897f8a9_0
  - libtheora=1.1.1=h1a28f6b_3
  - libtiff=4.7.0=h91aec0a_0
  - libvorbis=1.3.7=h1a28f6b_0
  - libvpx=1.13.1=h313beb8_0
  - libwebp=1.3.2=hf40cdb4_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown-it-py=4.0.0=py311hca03da5_1
  - matplotlib=3.10.6=py311hca03da5_1
  - matplotlib-base=3.10.6=py311h37b8ce2_1
  - matplotlib-inline=0.1.7=py311hca03da5_0
  - mdurl=0.1.2=py311hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py311hca03da5_0
  - numpy=2.3.4=py311h4bb6f22_1
  - numpy-base=2.3.4=py311h23175f9_1
  - openblas=0.3.30=openmp_hea878ba_3
  - openh264=2.1.1=h98b2900_0
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py311hca03da5_1
  - pango=1.50.7=hf2328af_2
  - parso=0.8.4=py311hca03da5_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=py311hca03da5_1
  - pillow=12.0.0=py311he2d6fe4_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=py311hca03da5_0
  - pluggy=1.5.0=py311hca03da5_0
  - prompt-toolkit=3.0.52=py311hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py311hca03da5_0
  - pygments=2.19.2=py311hca03da5_0
  - pyparsing=3.2.0=py311hca03da5_0
  - pytest=8.4.2=py311hca03da5_0
  - python=3.11.7=hb885b13_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - pythreejs=2.4.2=pyhbbac1ac_1
  - pyzmq=27.1.0=py311h5a8c52c_1
  - readline=8.3=h0b18652_0
  - rich=14.2.0=py311hca03da5_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=py311hca03da5_0
  - tesseract=5.2.0=h9e66425_3
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py311h80987f9_0
  - tqdm=4.67.1=py311hb6e6a13_0
  - traitlets=5.14.3=py311hca03da5_0
  - traittypes=0.2.3=pyh332efcf_0
  - trimesh=4.8.3=pyh7b2049a_0
  - typing_extensions=4.15.0=py311hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.13=py311hca03da5_0
  - wheel=0.45.1=py311hca03da5_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - nose==1.3.7
      - scipy==1.16.3
      - src==0.0.0
prefix: /opt/anaconda3/envs/spindle-simulations
